use std::error::Error;

pub async fn hello() -> Result<(), Box<dyn Error>> {
    // TODO
    Ok(())
}
